/*
 * System call numbers.
 *
 * DO NOT EDIT-- this file is automatically @generated.
 * $FreeBSD$
 */

#define	LINUX_SYS_linux_exit	1
#define	LINUX_SYS_linux_fork	2
#define	LINUX_SYS_read	3
#define	LINUX_SYS_write	4
#define	LINUX_SYS_linux_open	5
#define	LINUX_SYS_close	6
#define	LINUX_SYS_linux_creat	8
#define	LINUX_SYS_linux_link	9
#define	LINUX_SYS_linux_unlink	10
#define	LINUX_SYS_linux_execve	11
#define	LINUX_SYS_linux_chdir	12
#define	LINUX_SYS_linux_time	13
#define	LINUX_SYS_linux_mknod	14
#define	LINUX_SYS_linux_chmod	15
#define	LINUX_SYS_linux_lchown	16
#define	LINUX_SYS_linux_lseek	19
#define	LINUX_SYS_linux_getpid	20
#define	LINUX_SYS_linux_mount	21
#define	LINUX_SYS_linux_umount	22
#define	LINUX_SYS_setuid	23
#define	LINUX_SYS_linux_getuid	24
#define	LINUX_SYS_linux_ptrace	26
#define	LINUX_SYS_linux_alarm	27
#define	LINUX_SYS_linux_pause	29
#define	LINUX_SYS_linux_utime	30
#define	LINUX_SYS_linux_access	33
#define	LINUX_SYS_sync	36
#define	LINUX_SYS_linux_kill	37
#define	LINUX_SYS_linux_rename	38
#define	LINUX_SYS_linux_mkdir	39
#define	LINUX_SYS_linux_rmdir	40
#define	LINUX_SYS_dup	41
#define	LINUX_SYS_linux_pipe	42
#define	LINUX_SYS_linux_times	43
#define	LINUX_SYS_linux_brk	45
#define	LINUX_SYS_setgid	46
#define	LINUX_SYS_linux_getgid	47
#define	LINUX_SYS_geteuid	49
#define	LINUX_SYS_getegid	50
#define	LINUX_SYS_acct	51
#define	LINUX_SYS_linux_ioctl	54
#define	LINUX_SYS_linux_fcntl	55
#define	LINUX_SYS_setpgid	57
#define	LINUX_SYS_umask	60
#define	LINUX_SYS_chroot	61
#define	LINUX_SYS_linux_ustat	62
#define	LINUX_SYS_dup2	63
#define	LINUX_SYS_linux_getppid	64
#define	LINUX_SYS_getpgrp	65
#define	LINUX_SYS_setsid	66
#define	LINUX_SYS_setreuid	70
#define	LINUX_SYS_setregid	71
#define	LINUX_SYS_linux_sethostname	74
#define	LINUX_SYS_linux_setrlimit	75
#define	LINUX_SYS_linux_getrlimit	76
#define	LINUX_SYS_getrusage	77
#define	LINUX_SYS_gettimeofday	78
#define	LINUX_SYS_settimeofday	79
#define	LINUX_SYS_linux_getgroups	80
#define	LINUX_SYS_linux_setgroups	81
#define	LINUX_SYS_linux_select	82
#define	LINUX_SYS_linux_symlink	83
#define	LINUX_SYS_linux_readlink	85
#define	LINUX_SYS_swapon	87
#define	LINUX_SYS_linux_reboot	88
#define	LINUX_SYS_linux_mmap	90
#define	LINUX_SYS_munmap	91
#define	LINUX_SYS_linux_truncate	92
#define	LINUX_SYS_linux_ftruncate	93
#define	LINUX_SYS_fchmod	94
#define	LINUX_SYS_fchown	95
#define	LINUX_SYS_linux_getpriority	96
#define	LINUX_SYS_setpriority	97
#define	LINUX_SYS_linux_statfs	99
#define	LINUX_SYS_linux_fstatfs	100
#define	LINUX_SYS_linux_ioperm	101
#define	LINUX_SYS_linux_syslog	103
#define	LINUX_SYS_linux_setitimer	104
#define	LINUX_SYS_linux_getitimer	105
#define	LINUX_SYS_linux_newstat	106
#define	LINUX_SYS_linux_newlstat	107
#define	LINUX_SYS_linux_newfstat	108
#define	LINUX_SYS_linux_iopl	110
#define	LINUX_SYS_linux_vhangup	111
#define	LINUX_SYS_linux_wait4	114
#define	LINUX_SYS_linux_swapoff	115
#define	LINUX_SYS_linux_sysinfo	116
#define	LINUX_SYS_fsync	118
#define	LINUX_SYS_linux_clone	120
#define	LINUX_SYS_linux_setdomainname	121
#define	LINUX_SYS_linux_newuname	122
#define	LINUX_SYS_linux_modify_ldt	123
#define	LINUX_SYS_linux_adjtimex	124
#define	LINUX_SYS_linux_mprotect	125
#define	LINUX_SYS_linux_init_module	128
#define	LINUX_SYS_linux_delete_module	129
#define	LINUX_SYS_linux_quotactl	131
#define	LINUX_SYS_getpgid	132
#define	LINUX_SYS_fchdir	133
#define	LINUX_SYS_linux_personality	136
#define	LINUX_SYS_linux_setfsuid	138
#define	LINUX_SYS_linux_setfsgid	139
#define	LINUX_SYS_linux_llseek	140
#define	LINUX_SYS_linux_getdents	141
#define	LINUX_SYS_flock	143
#define	LINUX_SYS_linux_msync	144
#define	LINUX_SYS_readv	145
#define	LINUX_SYS_writev	146
#define	LINUX_SYS_linux_getsid	147
#define	LINUX_SYS_linux_fdatasync	148
#define	LINUX_SYS_linux_sysctl	149
#define	LINUX_SYS_mlock	150
#define	LINUX_SYS_munlock	151
#define	LINUX_SYS_mlockall	152
#define	LINUX_SYS_munlockall	153
#define	LINUX_SYS_linux_sched_setparam	154
#define	LINUX_SYS_linux_sched_getparam	155
#define	LINUX_SYS_linux_sched_setscheduler	156
#define	LINUX_SYS_linux_sched_getscheduler	157
#define	LINUX_SYS_sched_yield	158
#define	LINUX_SYS_linux_sched_get_priority_max	159
#define	LINUX_SYS_linux_sched_get_priority_min	160
#define	LINUX_SYS_linux_sched_rr_get_interval	161
#define	LINUX_SYS_linux_nanosleep	162
#define	LINUX_SYS_linux_mremap	163
#define	LINUX_SYS_setresuid	164
#define	LINUX_SYS_getresuid	165
#define	LINUX_SYS_linux_poll	167
#define	LINUX_SYS_setresgid	169
#define	LINUX_SYS_getresgid	170
#define	LINUX_SYS_linux_prctl	171
#define	LINUX_SYS_linux_rt_sigreturn	172
#define	LINUX_SYS_linux_rt_sigaction	173
#define	LINUX_SYS_linux_rt_sigprocmask	174
#define	LINUX_SYS_linux_rt_sigpending	175
#define	LINUX_SYS_linux_rt_sigtimedwait	176
#define	LINUX_SYS_linux_rt_sigqueueinfo	177
#define	LINUX_SYS_linux_rt_sigsuspend	178
#define	LINUX_SYS_linux_pread	179
#define	LINUX_SYS_linux_pwrite	180
#define	LINUX_SYS_linux_chown	181
#define	LINUX_SYS_linux_getcwd	182
#define	LINUX_SYS_linux_capget	183
#define	LINUX_SYS_linux_capset	184
#define	LINUX_SYS_linux_sigaltstack	185
#define	LINUX_SYS_linux_sendfile	186
#define	LINUX_SYS_linux_vfork	189
#define	LINUX_SYS_linux_mmap2	192
#define	LINUX_SYS_linux_getdents64	202
#define	LINUX_SYS_linux_pivot_root	203
#define	LINUX_SYS_linux_madvise	205
#define	LINUX_SYS_linux_mincore	206
#define	LINUX_SYS_linux_gettid	207
#define	LINUX_SYS_linux_tkill	208
#define	LINUX_SYS_linux_setxattr	209
#define	LINUX_SYS_linux_lsetxattr	210
#define	LINUX_SYS_linux_fsetxattr	211
#define	LINUX_SYS_linux_getxattr	212
#define	LINUX_SYS_linux_lgetxattr	213
#define	LINUX_SYS_linux_fgetxattr	214
#define	LINUX_SYS_linux_listxattr	215
#define	LINUX_SYS_linux_llistxattr	216
#define	LINUX_SYS_linux_flistxattr	217
#define	LINUX_SYS_linux_removexattr	218
#define	LINUX_SYS_linux_lremovexattr	219
#define	LINUX_SYS_linux_fremovexattr	220
#define	LINUX_SYS_linux_sys_futex	221
#define	LINUX_SYS_linux_sched_setaffinity	222
#define	LINUX_SYS_linux_sched_getaffinity	223
#define	LINUX_SYS_linux_set_tid_address	232
#define	LINUX_SYS_linux_fadvise64	233
#define	LINUX_SYS_linux_exit_group	234
#define	LINUX_SYS_linux_lookup_dcookie	235
#define	LINUX_SYS_linux_epoll_create	236
#define	LINUX_SYS_linux_epoll_ctl	237
#define	LINUX_SYS_linux_epoll_wait	238
#define	LINUX_SYS_linux_remap_file_pages	239
#define	LINUX_SYS_linux_timer_create	240
#define	LINUX_SYS_linux_timer_settime	241
#define	LINUX_SYS_linux_timer_gettime	242
#define	LINUX_SYS_linux_timer_getoverrun	243
#define	LINUX_SYS_linux_timer_delete	244
#define	LINUX_SYS_linux_clock_settime	245
#define	LINUX_SYS_linux_clock_gettime	246
#define	LINUX_SYS_linux_clock_getres	247
#define	LINUX_SYS_linux_clock_nanosleep	248
#define	LINUX_SYS_linux_tgkill	250
#define	LINUX_SYS_linux_utimes	251
#define	LINUX_SYS_linux_statfs64	252
#define	LINUX_SYS_linux_fstatfs64	253
#define	LINUX_SYS_linux_migrate_pages	258
#define	LINUX_SYS_linux_mbind	259
#define	LINUX_SYS_linux_get_mempolicy	260
#define	LINUX_SYS_linux_set_mempolicy	261
#define	LINUX_SYS_linux_mq_open	262
#define	LINUX_SYS_linux_mq_unlink	263
#define	LINUX_SYS_linux_mq_timedsend	264
#define	LINUX_SYS_linux_mq_timedreceive	265
#define	LINUX_SYS_linux_mq_notify	266
#define	LINUX_SYS_linux_mq_getsetattr	267
#define	LINUX_SYS_linux_kexec_load	268
#define	LINUX_SYS_linux_add_key	269
#define	LINUX_SYS_linux_request_key	270
#define	LINUX_SYS_linux_keyctl	271
#define	LINUX_SYS_linux_waitid	272
#define	LINUX_SYS_linux_ioprio_set	273
#define	LINUX_SYS_linux_ioprio_get	274
#define	LINUX_SYS_linux_inotify_add_watch	276
#define	LINUX_SYS_linux_inotify_rm_watch	277
#define	LINUX_SYS_linux_pselect6	280
#define	LINUX_SYS_linux_ppoll	281
#define	LINUX_SYS_linux_unshare	282
#define	LINUX_SYS_linux_splice	283
#define	LINUX_SYS_linux_tee	284
#define	LINUX_SYS_linux_vmsplice	285
#define	LINUX_SYS_linux_openat	286
#define	LINUX_SYS_linux_mkdirat	287
#define	LINUX_SYS_linux_mknodat	288
#define	LINUX_SYS_linux_fchownat	289
#define	LINUX_SYS_linux_futimesat	290
#define	LINUX_SYS_linux_newfstatat	291
#define	LINUX_SYS_linux_unlinkat	292
#define	LINUX_SYS_linux_renameat	293
#define	LINUX_SYS_linux_linkat	294
#define	LINUX_SYS_linux_symlinkat	295
#define	LINUX_SYS_linux_readlinkat	296
#define	LINUX_SYS_linux_fchmodat	297
#define	LINUX_SYS_linux_faccessat	298
#define	LINUX_SYS_linux_get_robust_list	299
#define	LINUX_SYS_linux_set_robust_list	300
#define	LINUX_SYS_linux_move_pages	301
#define	LINUX_SYS_linux_getcpu	302
#define	LINUX_SYS_linux_epoll_pwait	303
#define	LINUX_SYS_linux_utimensat	304
#define	LINUX_SYS_linux_timerfd_create	306
#define	LINUX_SYS_linux_eventfd	307
#define	LINUX_SYS_linux_sync_file_range	308
#define	LINUX_SYS_linux_fallocate	309
#define	LINUX_SYS_linux_timerfd_settime	311
#define	LINUX_SYS_linux_timerfd_gettime	312
#define	LINUX_SYS_linux_signalfd4	313
#define	LINUX_SYS_linux_eventfd2	314
#define	LINUX_SYS_linux_epoll_create1	315
#define	LINUX_SYS_linux_dup3	316
#define	LINUX_SYS_linux_pipe2	317
#define	LINUX_SYS_linux_inotify_init1	318
#define	LINUX_SYS_linux_perf_event_open	319
#define	LINUX_SYS_linux_preadv	320
#define	LINUX_SYS_linux_pwritev	321
#define	LINUX_SYS_linux_rt_tgsigqueueinfo	322
#define	LINUX_SYS_linux_fanotify_init	323
#define	LINUX_SYS_linux_fanotify_mark	324
#define	LINUX_SYS_linux_prlimit64	325
#define	LINUX_SYS_linux_socket	326
#define	LINUX_SYS_linux_bind	327
#define	LINUX_SYS_linux_connect	328
#define	LINUX_SYS_linux_listen	329
#define	LINUX_SYS_linux_accept	330
#define	LINUX_SYS_linux_getsockname	331
#define	LINUX_SYS_linux_getpeername	332
#define	LINUX_SYS_linux_socketpair	333
#define	LINUX_SYS_linux_sendto	335
#define	LINUX_SYS_linux_recvfrom	337
#define	LINUX_SYS_linux_shutdown	338
#define	LINUX_SYS_linux_setsockopt	339
#define	LINUX_SYS_linux_getsockopt	340
#define	LINUX_SYS_linux_sendmsg	341
#define	LINUX_SYS_linux_recvmsg	342
#define	LINUX_SYS_linux_recvmmsg	343
#define	LINUX_SYS_linux_accept4	344
#define	LINUX_SYS_linux_name_to_handle_at	345
#define	LINUX_SYS_linux_open_by_handle_at	346
#define	LINUX_SYS_linux_clock_adjtime	347
#define	LINUX_SYS_linux_syncfs	348
#define	LINUX_SYS_linux_sendmmsg	349
#define	LINUX_SYS_linux_setns	350
#define	LINUX_SYS_linux_process_vm_readv	351
#define	LINUX_SYS_linux_process_vm_writev	352
#define	LINUX_SYS_linux_finit_module	353
#define	LINUX_SYS_linux_kcmp	354
#define	LINUX_SYS_linux_sched_setattr	355
#define	LINUX_SYS_linux_sched_getattr	356
#define	LINUX_SYS_linux_renameat2	357
#define	LINUX_SYS_linux_seccomp	358
#define	LINUX_SYS_linux_getrandom	359
#define	LINUX_SYS_linux_memfd_create	360
#define	LINUX_SYS_linux_bpf	361
#define	LINUX_SYS_linux_execveat	362
#define	LINUX_SYS_linux_userfaultfd	364
#define	LINUX_SYS_linux_membarrier	365
#define	LINUX_SYS_linux_mlock2	378
#define	LINUX_SYS_linux_copy_file_range	379
#define	LINUX_SYS_linux_preadv2	380
#define	LINUX_SYS_linux_pwritev2	381
#define	LINUX_SYS_linux_statx	383
#define	LINUX_SYS_linux_pkey_alloc	384
#define	LINUX_SYS_linux_pkey_free	385
#define	LINUX_SYS_linux_pkey_mprotect	386
#define	LINUX_SYS_linux_rseq	387
#define	LINUX_SYS_linux_io_pgetevents	388
#define	LINUX_SYS_linux_semtimedop	392
#define	LINUX_SYS_linux_semget	393
#define	LINUX_SYS_linux_semctl	394
#define	LINUX_SYS_linux_shmget	395
#define	LINUX_SYS_linux_shmctl	396
#define	LINUX_SYS_linux_shmat	397
#define	LINUX_SYS_linux_shmdt	398
#define	LINUX_SYS_linux_msgget	399
#define	LINUX_SYS_linux_msgsnd	400
#define	LINUX_SYS_linux_msgrcv	401
#define	LINUX_SYS_linux_msgctl	402
#define	LINUX_SYS_linux_pidfd_send_signal	424
#define	LINUX_SYS_linux_io_uring_setup	425
#define	LINUX_SYS_linux_io_uring_enter	426
#define	LINUX_SYS_linux_io_uring_register	427
#define	LINUX_SYS_linux_open_tree	428
#define	LINUX_SYS_linux_move_mount	429
#define	LINUX_SYS_linux_fsopen	430
#define	LINUX_SYS_linux_fsconfig	431
#define	LINUX_SYS_linux_fsmount	432
#define	LINUX_SYS_linux_fspick	433
#define	LINUX_SYS_linux_pidfd_open	434
#define	LINUX_SYS_linux_clone3	435
#define	LINUX_SYS_linux_close_range	436
#define	LINUX_SYS_linux_openat2	437
#define	LINUX_SYS_linux_pidfd_getfd	438
#define	LINUX_SYS_linux_faccessat2	439
#define	LINUX_SYS_linux_process_madvise	440
#define	LINUX_SYS_linux_epoll_pwait2	441
#define	LINUX_SYS_linux_mount_setattr	442
#define	LINUX_SYS_MAXSYSCALL	451
